<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Encore" Version="1.0.0" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Ini" Version="10.0.2" />
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
        <PackageVersion Include="System.CommandLine" Version="2.0.2" />
    </ItemGroup>
</Project>
